---
# Standalone installation is required for builds using buildtools 26 and later
- name: Ensure gradle is installed
  homebrew:
    name: gradle
    state: present

- name: Ensure android-commandlinetools is installed
  homebrew_cask:
    name: android-commandlinetools
    state: present

- name: Ensure ~/.android is created
  file:
    path: ~/.android
    state: directory

- name: Ensure ~/.android/repositories.cfg is created
  file:
    path: ~/.android/repositories.cfg
    state: touch

- name: Ensure ~/.android-sdk is nuked
  file:
    path: ~/.android-sdk
    state: absent

- name: Ensure specified packages are installed
  shell: $SHELL -lc "echo y | sdkmanager --sdk_root={{ ansible_env.HOME }}/.android-sdk \"{{ item }}\""
  loop: "{{ android_sdk_packages }}"

- name: Ensure android-sdk is added to user's profile
  blockinfile:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.zprofile"
    block: "{{ lookup('template', 'android-sdk.sh.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK -- ANDROID-SDK"
