---
# Standalone installation is required for builds using buildtools 26 and later
- name: Ensure gradle is installed
  homebrew:
    name: gradle
    state: present

- name: Ensure android-sdk is installed
  homebrew_cask:
    name: android-sdk
    state: present

- name: Ensure ~/.android is created
  file:
    path: ~/.android
    state: directory

- name: Ensure ~/.android/repositories.cfg is created
  file:
    path: ~/.android/repositories.cfg
    state: touch

- name: Ensure specified packages are installed
  shell: $SHELL -lc "echo y | sdkmanager --sdk_root={{ ansible_env.HOME }}/.android-sdk \"{{ item }}\""
  loop: "{{ android_sdk_packages }}"

- name: Ensure android-sdk is added to profile system-wide
  blockinfile:
    path: /etc/profile
    block: "{{ lookup('template', 'android-sdk.sh.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK -- ANDROID-SDK"
  become: yes